<div class="col s12 m7">
  <h2 class="header">Cliente: <?= $client->name ?></h2>
  <div class="card horizontal">
    <div class="card-image">
      <img id="image_preview" src="<?= $client->avatar()->path() ?>" alt="Client Avatar">
    </div>
    <div class="card-stacked">
      <div class="card-content">
        <div class="divider"></div>
        <div class="section">
          <h5>Telefone</h5>
          <p><?= $client->phone ?></p>
        </div>
        <div class="divider"></div>
        <div class="section">
          <h5>Convênio</h5>
          <p><?= $client->insurance_id ?></p>
        </div>
        <div class="divider"></div>
        <div class="section">
          <h5>Endereço</h5>
          <p>Cidade: <?= $client->city_id ?></p>
          <p>Rua: <?= $client->street_name ?></p>
        </div>
      </div>
      <div class="card-action">
        <a href="/clients">Voltar</a>
      </div>
    </div>
  </div>
</div>

<form action="<?= route("profile.avatar.client")?>" method="POST" enctype="multipart/form-data">
  <input id="image_preview_input" type="file" name="client_avatar" id="user_avatar">
  <button id="image_preview_submit" style="display: none;">Atualizar Foto</button>
  </form>
