<section>
  <div class="row">
    <form action="<?= route("client.update", ["id" => $client->id]) ?>" method="POST" class="col s12">
      <div class="row">
        <div class="input-field col s12 m3 l6">
          <input type="hidden" name="_method" value="PUT">
          <input value="<?= $client->name ?>" placeholder="Novo Nome" id="newClienteName" type="text" class="validate" name="client[name]" required>
          <label for="newClienteName">Editar Nome Cliente <?= $client->id ?></label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input type="hidden" name="_method" value="PUT">
          <input value="<?= $client->phone ?>" placeholder="NovoTelefone" id="newClientePhone" type="text" class="validate" name="client[phone]" required>
          <label for="newClientePhone">Telefone</label>
        </div>

        <div class="input-field col s12 m12 l12">
          <input type="hidden" name="_method" value="PUT">
          <select name="client[insurance_id]">
            <?php foreach ($insurances as $insurance) : ?>
              <option value="<?= $insurance->id ?>"><?= $insurance->name ?></option>
            <?php endforeach ?>
          </select>
          <label>Selecionar O Convenio</label>
        </div>

        <div class="input-field col s12 m3 l3">
          <input type="hidden" name="_method" value="PUT">
          <input value="<?= $client->street_name?>" placeholder="newClientStreetName" id="newClientStreetName" type="text" class="validate" name="client[street_name]" required>
          <label for="newClientStreetName">Endereço</label>
        </div>

        <div class="input-field col s12 m3 l3">
          <input type="hidden" name="_method" value="PUT">
          <input value="<?= $client->number ?>" placeholder="newClientNumberHouse" id="newClientNumberHouse" type="text" class="validate" name="client[number]" required>
          <label for="newClientNumberHouse">numero</label>
        </div>

        <div class="input-field col s12 m3 l3">
          <input type="hidden" name="_method" value="PUT">
          <select name="client[city_id]">
            <?php foreach ($citys as $city) : ?>
              <option value="<?= $city->id ?>"><?= $city->name ?></option>
            <?php endforeach ?>
          </select>
          <label>Selecionar a Cidade</label>
        </div>

      </div>
      <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
    </form>
  </div>
</section>
