<section>
  <div class="row">
    <form action="<?= route("create.client") ?>" method="POST" class="col s12">
      <div class="row">
        <div class="input-field col s12 m12 l6">
          <input placeholder="Exemplo: Ana" id="client_name" type="text" class="validate" name="client[name]" required>
          <label for="client_name">Nome Cliente:</label>
        </div>
        <div class="input-field col s12 m12 l6">
          <input placeholder="42991999" id="client_phone" type="text" class="validate" name="client[phone]" required>
          <label for="client_phone">Telefone:</label>
        </div>
        <div class="input-field col s12 m12 l6">
          <select name="client[insurance_id]">
            <?php foreach ($insurances as $insurance) : ?>
              <option value="<?= $insurance->id ?>"><?= $insurance->name ?></option>
            <?php endforeach ?>
          </select>
          <label>Selecionar O Convenio</label>
        </div>
        <div class="input-field col s12 m12 l6">
          <input placeholder="Exemplo:Rua 1 " id="client_street" type="text" class="validate" name="client[street_name]" required>
          <label for="client_street">Rua:</label>
        </div>
        <div class="input-field col s12 m12 l6">
          <input placeholder="255" id="number_house" type="number" class="validate" name="client[number]" required>
          <label for="number_house">numero:</label>
        </div>
        <div class="input-field col s12 m12 l6">
        <select name="client[city_id]">
            <?php foreach ($citys as $city) : ?>
              <option value="<?= $city->id ?>"><?= $city->name ?></option>
            <?php endforeach ?>
          </select>
          <label>Selecionar a Cidade</label>
        </div>
      </div>
      <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
    </form>
  </div>
</section>
