<section>
  <div>
    <h4>Horários</h4>
    <a href="<?= route("schedule.new") ?>"><button class="btn waves-effect waves-light green " type="submit" name="action">Novo
      </button></a>
  </div>
  <table class="centered  responsive-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Psicologo</th>
        <th>Dia Semana</th>
        <th>Inicio</th>
        <th>Fim</th>
      </tr>
    </thead>
    <?php foreach ($fixedSchedules as $fixedSchedule) : ?>
      <tbody>
        <tr>
          <td><?= $fixedSchedule->getID() ?></td>
          <td><?= $fixedSchedule->getUserID() ?></td>
          <td><?= $fixedSchedule->getDayOFWeek() ?></td>
          <td><?= $fixedSchedule->getStartTime()->format('H:i:s') ?></td>
          <td><?= $fixedSchedule->getEndTime()->format('H:i:s') ?></td>
          <td>
            <div class="left">
              <a href="<?= route("schedule.edit", ["id" => $fixedSchedule->getID()]) ?>" class="right yellow accent-4 waves-effect waves-light btn-small"><i class="material-icons center">edit</i></a>

              <a href="<?= route("schedule.show", ["id" => $fixedSchedule->getID()]) ?>" class="right blue accent-4 waves-effect waves-light btn-small"><i class="material-icons center">search</i></a>
            </div>
            <form action="<?= route("schedules.list", ["id" => $fixedSchedule->getID()]) ?>" method="POST">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="id_delete" value="<?= route("schedule.destroy", ["id" => $fixedSchedule->getId()]) ?>">
              <button class="waves-effect waves-light btn-small red" type="submit"><i class="material-icons center">delete</i></button>
            </form>
          </td>
        </tr>
      </tbody>
    <?php endforeach ?>
  </table>
</section>