<div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><?="Cliente".$appointment->client_id?></span>
          <p><?="Data: ".$appointment->date?> </p>
          <p><?="Horário Inicio: ".$appointment->start_time?></p>
          <p><?="Horário Termino: ".$appointment->end_time?></p>
          <p><?="Responsável: ".$appointment->psychologist_id?></p>
        </div>
        <div class="card-action">
          <a href="/appointaments">Voltar</a>
        </div>
      </div>
    </div>
  </div>