<div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><?="Agendamento".$appointment->getClientID()?></span>
          <p><?="Data: ".$appointment->getDate()->format("D:M:Y")?> </p>
          <p><?="Horário Inicio: ".$appointment->getStartHour()->format("H:i:s")?></p>
          <p><?="Horário Termino: ".$appointment->getEndDate()->format("H:i:s")?></p>
          <p><?="Responsável: ".$appointment->getUserID() ?></p>
        </div>
        <div class="card-action">
          <a href="/appointaments">Voltar</a>
        </div>
      </div>
    </div>
  </div>