<!-- edita   -->
<section>
    <div class="row">
        <h4>Editar Agendamento #<?= $appointment->id ?></h4>
        <form action="<?= route("appointaments.update", ["id" => $appointment->id]) ?>" method="POST" class="col s12">
            <div class="row">
                <input type="hidden" name="_method" value="PUT">
                <div class="input-field col s12 m6">
                    <input value="<?= $appointment->psychologist_id  ?>" id="newUserID" type="text" class="validate" name="newUserID" required>
                    <label for="newUserID">Editar Responsável</label>
                </div>
                <div class="input-field col s12 m6">
                    <input value="<?= (new DateTime($appointment->date))->format("d/m/Y") ?>" id="newDate" type="text" class="validate" name="newDate" required>
                    <label for="newDate">Nova Data</label>
                </div>
                <div class="input-field col s12 m6">
                    <input value="<?= (new DateTime($appointment->start_time))->format("H:i:s") ?>" id="newStartHour" type="text" class="validate" name="newStartHour" required>
                    <label for="newStartHour">Novo Horário Início</label>
                </div>
                <div class="input-field col s12 m6">
                    <input value="<?= (new DateTime($appointment->end_time))->format("H:i:s") ?>" id="newEndHours" type="text" class="validate" name="newEndHours" required>
                    <label for="newEndHours">Novo Horário Término</label>
                </div>
                <div class="input-field col s12 m6">
                    <input value="<?= $appointment->client_id ?>" id="newClientID" type="text" class="validate" name="newClientID" required>
                    <label for="newClientID">Alteração Cliente</label>
                </div>
            </div>
            <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
        </form>
    </div>
</section>
