<section>
    <div>
        <h4>Agendamentos</h4>
        <a href="<?= route("appointament.new") ?>"><button class="btn waves-effect waves-light green " type="submit" name="action">Novo
            </button></a>
    </div>
    <?php foreach ($appointments as $appointment) : ?>
        <div class="row">
            <div class="col s12 m6">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title"><?= $appointment->getUserID() ?></span>
                    </div>
                    <div class="card-action">
                        <a href="<?= route("appointaments.show", ["id" => $appointment->getId()]) ?>" class="right blue accent-4 waves-effect waves-light btn-small"><i class="material-icons center">search</i></a>

                        <a href="<?= route("appointaments.edit", ["id" => $appointment->getId()]) ?>" class="right yellow accent-4 waves-effect waves-light btn-small"><i class="material-icons center">edit</i></a>
                        <div class="right">
                            <form action="<?= route("appointament.destroy", ["id" => $appointment->getId()]) ?>" method="POST">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="id_delete" value="<?= route("appointament.destroy", ["id" => $appointment->getId()]) ?>">
                                <button class="waves-effect waves-light btn-small red" type="submit"><i class="material-icons center">delete</i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</section>
<div class="center">
    <?php $paginator->renderPagesNavigation() ?>
</div>