<section>
    <div>
        <h4>Agendamentos</h4>
        <a href="<?= route("appointament.new") ?>"><button class="btn waves-effect waves-light green " type="submit" name="action">Novo
            </button></a>
    </div>
    <?php foreach ($appointments as $appointment) : ?>
        <div class="row">
            <div class="col s12 m6">
                <div class="card blue-grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title"><?=$appointment->getUserId()?></span>
                    </div>
                    <div class="card-action">
                        <a href="#">This is a link</a>
                        <a href="#">This is a link</a>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</section>
<div class="center">
    <?php $paginator->renderPagesNavigation() ?>
</div>