<section>
  <div class="row">
    <form action="<?= route("create.appointaments") ?>" method="POST" class="col s12">
      <div class="row">
        <div class="input-field col s12 m12 l6">
          <select name="appointment[psychologist_id]">
            <?php if ($isMaster) : ?>
              <?php foreach ($users as $user) : ?>
                <option value="<?= $user->id ?>"><?= $user->name ?></option>
              <?php endforeach ?>
            <?php else : ?>
              <option value="<?= $user->id ?>"><?= $user->name ?></option>
            <?php endif ?>
          </select>
          <label>Selecionar o Responśavel</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input id="date" type="date" class="validate" name="appointment[date]" required>
          <label for="date">Data</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input id="startHour" type="text" class="validate" name="appointment[start_time]" required>
          <label for="startHour">Horário Inicio</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input id="hours" type="text" class="validate" name="appointment[end_time]" required>
          <label for="hours">Horário Termino</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <select name="appointment[client_id]">
            <?php foreach ($clients as $client) : ?>
              <option value="<?= $client->id ?>"><?= $client->name ?></option>
            <?php endforeach ?>
          </select>
          <label>Selecionar o Cliente</label>
        </div>

      </div>
      <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
    </form>
  </div>
</section>