<section>
  <div class="row">
    <form action="<?= route("create.appointaments")?>" method="POST" class="col s12">
      <div class="row">
        <div class="input-field col s12 m12 l6">
          <input  id="userID" type="text" class="validate" name="appointment[psychologist_id]" required>
          <label for="userID">Responśavel</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input  id="date" type="text" class="validate" name="appointment[date]" required>
          <label for="date">Data</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input  id="startHour" type="text" class="validate" name="appointment[start_time]" required>
          <label for="startHour">Horário Inicio</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input  id="hours" type="text" class="validate" name="appointment[end_time]" required>
          <label for="hours">Horário Termino</label>
        </div>

        <div class="input-field col s12 m12 l6">
          <input  id="hours" type="text" class="validate" name="appointment[client_id]" required>
          <label for="clientID">Cliente</label>
        </div>
        
      </div>
      <button class="waves-effect waves-light btn blue" type="submit">Salvar</button>
    </form>
  </div>
</section>
