<div class="container">
  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <!-- Image preview area -->
          <img id="image_preview" src="<?=$this->current_user->avatar()->path()?>" alt="User Avatar">
          <span class="card-title black"><?=$this->current_user->name?></span>
        </div>
        <div class="card-content">
          <p>Email: <?=$this->current_user->email?></p>
        </div>
        <div class="card-action">
          <a href="/clients">Voltar</a>
        </div>
      </div>
    </div>
  </div>

  <form action="<?= route("profile.avatar")?>" method="POST" enctype="multipart/form-data">
  <input id="image_preview_input" type="file" name="user_avatar" id="user_avatar">
  <button id="image_preview_submit" style="display: none;">Atualizar Foto</button>
  </form>
</div>
