<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="/assets/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="/assets/js/materialize.min.js"></script>
  <script src="/assets/js/application.js"></script>
</head>

<body>
  <section>
    <nav>

      <div class="nav-wrapper blue darken-4">
        <a class="brand-logo center">BePsicologia</a>
        <?php if ($this->currentUser()) : ?>
          <ul id="nav-mobile" class="left ">
            <li><a href="<?= route("clients.list") ?>">Clientes</a></li>
            <li><a href="<?= route("schedules.list") ?>">Horários</a></li>
            <li><a href="<?= route("list.appointaments") ?>">Agendamentos</a></li>
          </ul>

          <ul id="nav-mobile" class="right ">
            <li><span class="white-text"><?=$this->currentUser()->name?></span></li>
            <li><a href="<?= route("profile.show") ?>">Perfil</a></li>
            <li><a href="<?= route("logout") ?>"><button class="waves-effect waves-light btn-flat red darken-1"><span class="white-text">SAIR</span></button></a></li>
          </ul>
        <?php endif; ?>
      </div>
    </nav>
  </section>
  <br>
  <div class="container">
    <nav>
      <div class="nav-wrapper blue darken-4 center">  </div>
    </nav>
    <br>
    <?php require "_flashMessage.phtml"; ?>
    <?php require $view ?>
  </div>
</body>

</html>
